### ISSUE TITLE
Switch to REST API instead of cloud profile editing via the web interface

### ISSUE THREAD

**Issue by pavelsher** [OctopusDeploy/TeamCityCloudAgentUpdater#1]
Since 2017.1 it is possible to use REST API to work with cloud profiles. Cloud profile is represented as a project feature, and project features are fully editable via the REST: https://confluence.jetbrains.com/display/TCD10/REST+API#RESTAPI-ProjectFeatures

Please consider switching to REST API instead of a error prone editing via the web interface.

**Comment by matt-richardson** [comment]
This is now done.
